package model;
// Generated 19 feb 2023 20:26:35 by Hibernate Tools 4.3.6.Final

/**
 * Partidos generated by hbm2java
 */
public class Partidos implements java.io.Serializable {

	private Integer codigo;
	private Equipo equipoByEquipoVisitante;
	private Equipo equipoByEquipoLocal;
	private int puntosLocal;
	private int puntosVisitante;
	private String temporada;

	public Partidos() {
	}

	public Partidos(Equipo equipoByEquipoVisitante, Equipo equipoByEquipoLocal, int puntosLocal, int puntosVisitante) {
		this.equipoByEquipoVisitante = equipoByEquipoVisitante;
		this.equipoByEquipoLocal = equipoByEquipoLocal;
		this.puntosLocal = puntosLocal;
		this.puntosVisitante = puntosVisitante;
	}

	public Partidos(Equipo equipoByEquipoVisitante, Equipo equipoByEquipoLocal, int puntosLocal, int puntosVisitante,
			String temporada) {
		this.equipoByEquipoVisitante = equipoByEquipoVisitante;
		this.equipoByEquipoLocal = equipoByEquipoLocal;
		this.puntosLocal = puntosLocal;
		this.puntosVisitante = puntosVisitante;
		this.temporada = temporada;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public Equipo getEquipoByEquipoVisitante() {
		return this.equipoByEquipoVisitante;
	}

	public void setEquipoByEquipoVisitante(Equipo equipoByEquipoVisitante) {
		this.equipoByEquipoVisitante = equipoByEquipoVisitante;
	}

	public Equipo getEquipoByEquipoLocal() {
		return this.equipoByEquipoLocal;
	}

	public void setEquipoByEquipoLocal(Equipo equipoByEquipoLocal) {
		this.equipoByEquipoLocal = equipoByEquipoLocal;
	}

	public int getPuntosLocal() {
		return this.puntosLocal;
	}

	public void setPuntosLocal(int puntosLocal) {
		this.puntosLocal = puntosLocal;
	}

	public int getPuntosVisitante() {
		return this.puntosVisitante;
	}

	public void setPuntosVisitante(int puntosVisitante) {
		this.puntosVisitante = puntosVisitante;
	}

	public String getTemporada() {
		return this.temporada;
	}

	public void setTemporada(String temporada) {
		this.temporada = temporada;
	}

}
